spring:
  application:
    name: eligibility

  profiles:
    active: dev

  r2dbc:
    url: r2dbc:h2:mem:///db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  liquibase:
    enabled: true
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    change-log: classpath:/db/changelog/changelog.xml

  sql:
    init:
      mode: never

  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.web: DEBUG
    cz.matej.parizek: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

external:
  clients:
    base-url: http://localhost:8082
    api-key: 1234567890abcdef1234567890abcdef
  accounts:
    base-url: http://localhost:8081
    api-key: 1234567890abcdef1234567890abcdef

